# This is how you access the deployment, using a service
# cat << EOF | kubectl apply -f -
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
# EOF